site_name: Future Fluent
site_author: Karol Jezierski
site_url: https://kajzer.github.io/future-fluent/                 
repo_url: https://github.com/kajzer/future-fluent
repo_name: kajzer.github.io/future-fluent/

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/robot
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.highlight
    - search.suggest
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.tooltips
    - content.action.edit
    - content.action.view

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: teal
      accent: green

extra:
  alternate:
    - name: English
      link: /future-fluent/ 
      lang: en
    - name: Polski
      link: /future-fluent/pl/
      lang: pl
  social:
    - icon: simple/linkedin
      link: https://linkedin.com/in/karol-jezierski

copyright: Copyright &copy; 2025 Karol Jezierski

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - footnotes

nav:
  - Home: index.md
  - Tutorials:
    - Prompt Engineering:
      - Tutorials/Prompt_Engineering/index.md
      - For Everyone:
        - Tutorials/Prompt_Engineering/For_Everyone/index.md
        - Tutorials/Prompt_Engineering/For_Everyone/getting_started.md
  - Docs:
    - LLM: 
      - Docs/LLM/index.md
    - Prompt Engineering:
      - Papers:
        - Docs/Prompt_Engineering/Papers/index.md

plugins:
  - search:
      lang: 
        - en
        - pl
  # - tags
  - awesome-pages
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pl
          name: Polski
          build: true
          nav_translations:
            Home: Strona Główna
            Tutorials: Tutoriale
            For Everyone: Dla Każdego
            Papers: Papery
