site_name: GenAI
site_url: https://kajzer.github.io/future-fluent/                 
repo_url: https://github.com/kajzer/future-fluent
repo_name: squidfunk/mkdocs-material

theme:
  name: material
  language: en
  font:
    # text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/robot
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.highlight
    - search.suggest
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: green

extra:
  alternate:
    - name: English
      link: / 
      lang: en
    - name: Polski
      link: /future-fluent/pl/
      lang: pl
  social:
    - icon: simple/linkedin
      link: https://linkedin.com/in/karol-jezierski

copyright: Copyright &copy; 2025 Karol Jezierski

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials/index.md
    - Prompt Engineering:
      - Basics:
        - Tutorials/Prompt_Engineering/Basics/index.md
        - Tutorials/Prompt_Engineering/Basics/getting_started.md
  - Docs:
    - Prompt Engineering:
      - Docs/Prompt_Engineering/index.md

plugins:
  - search
  # - tags
  - awesome-pages
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pl
          name: Polski
          build: true
          nav_translations:
            Home: Strona Główna
            Tutorials: Tutoriale
            Basics: Podstawy
